export cloudsql_credential_filename = serlo-staging-cloudsql-f5977dd586e0.json
export env_name = staging
export mysql_instance=10072019-1
export postgres_instance=10072019-2

include ../gcloud.mk
include ../terraform.mk
