image:
  tag: ${image_tag}
host: ${host}
replicaCount: ${app_replicas}.0
minAvailable: 1
externalMongodbUrl: ${mongodb_uri}
externalMongodbOplogUrl: ${mongodb_oplog_uri}
smtp:
  enabled: true
  host: ${smtp_host}
  port: ${smtp_port}
  username: ${smtp_username}
  password: ${smtp_password}

resources:
  requests:
    cpu: 300m
    memory: 1000Mi
  limits:
    cpu: 350m
    memory: 1500Mi

mongodb:
  enabled: false
