image:
  tag: ${image_tag}
architecture: replicaset
nodeSelector:
  cloud.google.com/gke-nodepool: ${node_pool}
auth:
  rootPassword: ${mongodb_root_password}
  username: ${mongodb_username}
  password: ${mongodb_password}
  database: ${mongodb_database}
  replicaSetKey: ${mongodb_replica_set_key}
resources:
  requests:
    cpu: 100m
    memory: 2000Mi
  limits:
    cpu: 150m
    memory: 2500Mi
