image:
  tag: ${image_tag}
architecture: replicaset
nodeSelector:
  cloud.google.com/gke-nodepool: ${node_pool}
auth:
  rootPassword: ${mongodb_root_password}
  username: ${mongodb_username}
  password: ${mongodb_password}
  database: ${mongodb_database}
  replicaSetKey: ${mongodb_replica_set_key}
readinessProbe:
  timeoutSeconds: 20
resources:
  requests:
    cpu: 200m
    memory: 500Mi
  limits:
    cpu: 250m
    memory: 1000Mi
