image:
  tag: 7.0.2
architecture: standalone
global:
  storageClass: standard
auth:
  rootPassword: ${mongodb_root_password}
resources:
  requests:
    cpu: 400m
    memory: 300Mi
  limits:
    cpu: 600m
    memory: 500Mi
