image:
  tag: 7.0.2
architecture: standalone
global:
  storageClass: standard
auth:
  rootPassword: ${mongodb_root_password}
resources:
  requests:
    cpu: 300m
    memory: 300Mi
  limits:
    cpu: 500m
    memory: 400Mi
